=== AdheenaBabu/19301_Eval1/form.dtd
<!ELEMENT recommendation (recommender*)>
<!ELEMENT recommender (firstname, lastname, organization, title, relation, phone, email, academic, intellectual, express, motivation, admit, sign)>
<!ATTLIST recommender prefix (Dr|Mr|Ms|Mrs) #REQUIRED>
<!ELEMENT firstname (#PCDATA) #REQUIRED>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT organization (#PCDATA) #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT relation (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT academic (#PCDATA)>
<!ELEMENT intellectual (#PCDATA)>
<!ELEMENT express (#PCDATA)>
<!ELEMENT motivation (#PCDATA)>
<!ELEMENT admit(#PCDATA)>
<!ELEMENT sign (#PCDATA) #REQUIRED>

=== AdheenaBabu/19301_Eval1/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recommendation SYSTEM "form.dtd">
<recommendation>
    <recommender prefix="Mr">
        <firstname>Sam</firstname>
        <lastname>T</lastname>
        <organization>Amrita University</organization>
        <title>Associate Professor</title>
        <relation>Associate Professor</relation>
        <phone>99999999</phone>
        <email>sam@gmail.com</email>
        <academic>Upper 50%</academic>
        <intellectual>Upper 25%</intellectual>
        <express>Upper 1 to 2%</express>
        <motivation>Upper 10%</motivation>
        <admit>No</admit>
        <sign>Sam T</sign>
    </recommender>
</recommendation>
